spring:
  application:
    name: the-investorthing-bff
    version: 0.1.1
    module: BFF
    author: Alessandro De Vincenti
  profiles:
    active: dev

---
spring:
  config:
    activate:
      on-profile: dev
server:
  port: 8082

---
spring:
  config:
    activate:
      on-profile: prod
server:
  port: 8080